package cliente;


import entity.Painel;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.border.LineBorder;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cliente.java
 *
 * Created on 07/06/2011, 16:46:54
 */

/**
 *
 * @author oziel
 */
public class Cliente extends javax.swing.JFrame {

    private Socket socket;
    private ObjectInputStream input;
    private ObjectOutputStream output;
    private Painel p;

    /** Creates new form Cliente */
    public Cliente() {
        initComponents();
        brushColor = Color.BLACK;
        colorBlack.setBorder(new LineBorder(Color.BLUE));
        brushType = 1;
        brushTypeRound.setBorder(new LineBorder(Color.BLUE));
        brushSize = 5;
        brushSize5.setBorder(new LineBorder(Color.BLUE));
        conexao = new Conexao(jPanel2.getGraphics());
    }

    public void initConexao(){
        try {
            //byte[] address = {(byte)0,(byte)0,(byte)0,(byte)0};
            socket = new Socket("127.0.0.1", 587);
            input = new ObjectInputStream(socket.getInputStream());
            output = new ObjectOutputStream(socket.getOutputStream());
            while (socket.isConnected()) {
                try {
                    p = (Painel) input.readObject();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        colorBlack = new javax.swing.JPanel();
        colorWhite = new javax.swing.JPanel();
        colorGray = new javax.swing.JPanel();
        colorLightGray = new javax.swing.JPanel();
        colorCyan = new javax.swing.JPanel();
        colorDarkCyan = new javax.swing.JPanel();
        colorLightBlue = new javax.swing.JPanel();
        colorBlue = new javax.swing.JPanel();
        colorLightPink = new javax.swing.JPanel();
        colorBrown = new javax.swing.JPanel();
        colorDarkBlue = new javax.swing.JPanel();
        colorLightBrown = new javax.swing.JPanel();
        colorNavy = new javax.swing.JPanel();
        colorPurple = new javax.swing.JPanel();
        colorLightPurple = new javax.swing.JPanel();
        colorPink = new javax.swing.JPanel();
        colorDarkGreen = new javax.swing.JPanel();
        colorRed = new javax.swing.JPanel();
        colorOrange = new javax.swing.JPanel();
        colorDarkYellow = new javax.swing.JPanel();
        colorYellow = new javax.swing.JPanel();
        colorGreen = new javax.swing.JPanel();
        brushTypeRound = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        brushTypeSquare = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        brushSize1 = new javax.swing.JPanel();
        brushSize5 = new javax.swing.JPanel();
        brushSize10 = new javax.swing.JPanel();
        brushSize15 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 579));

        colorBlack.setBackground(new java.awt.Color(0, 0, 0));
        colorBlack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorBlack.setPreferredSize(new java.awt.Dimension(30, 30));
        colorBlack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBlackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBlackLayout = new javax.swing.GroupLayout(colorBlack);
        colorBlack.setLayout(colorBlackLayout);
        colorBlackLayout.setHorizontalGroup(
            colorBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorBlackLayout.setVerticalGroup(
            colorBlackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorWhite.setBackground(new java.awt.Color(255, 255, 255));
        colorWhite.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorWhite.setPreferredSize(new java.awt.Dimension(30, 30));
        colorWhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorWhiteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorWhiteLayout = new javax.swing.GroupLayout(colorWhite);
        colorWhite.setLayout(colorWhiteLayout);
        colorWhiteLayout.setHorizontalGroup(
            colorWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorWhiteLayout.setVerticalGroup(
            colorWhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorGray.setBackground(new java.awt.Color(102, 102, 102));
        colorGray.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorGray.setPreferredSize(new java.awt.Dimension(30, 30));
        colorGray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorGrayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorGrayLayout = new javax.swing.GroupLayout(colorGray);
        colorGray.setLayout(colorGrayLayout);
        colorGrayLayout.setHorizontalGroup(
            colorGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorGrayLayout.setVerticalGroup(
            colorGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorLightGray.setBackground(new java.awt.Color(204, 204, 204));
        colorLightGray.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorLightGray.setPreferredSize(new java.awt.Dimension(30, 30));
        colorLightGray.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLightGrayMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorLightGrayLayout = new javax.swing.GroupLayout(colorLightGray);
        colorLightGray.setLayout(colorLightGrayLayout);
        colorLightGrayLayout.setHorizontalGroup(
            colorLightGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorLightGrayLayout.setVerticalGroup(
            colorLightGrayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorCyan.setBackground(new java.awt.Color(0, 255, 255));
        colorCyan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorCyan.setPreferredSize(new java.awt.Dimension(30, 30));
        colorCyan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorCyanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorCyanLayout = new javax.swing.GroupLayout(colorCyan);
        colorCyan.setLayout(colorCyanLayout);
        colorCyanLayout.setHorizontalGroup(
            colorCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorCyanLayout.setVerticalGroup(
            colorCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorDarkCyan.setBackground(new java.awt.Color(0, 51, 51));
        colorDarkCyan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorDarkCyan.setPreferredSize(new java.awt.Dimension(30, 30));
        colorDarkCyan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorDarkCyanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorDarkCyanLayout = new javax.swing.GroupLayout(colorDarkCyan);
        colorDarkCyan.setLayout(colorDarkCyanLayout);
        colorDarkCyanLayout.setHorizontalGroup(
            colorDarkCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorDarkCyanLayout.setVerticalGroup(
            colorDarkCyanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorLightBlue.setBackground(new java.awt.Color(0, 153, 255));
        colorLightBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorLightBlue.setPreferredSize(new java.awt.Dimension(30, 30));
        colorLightBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLightBlueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorLightBlueLayout = new javax.swing.GroupLayout(colorLightBlue);
        colorLightBlue.setLayout(colorLightBlueLayout);
        colorLightBlueLayout.setHorizontalGroup(
            colorLightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorLightBlueLayout.setVerticalGroup(
            colorLightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorBlue.setBackground(new java.awt.Color(0, 0, 255));
        colorBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorBlue.setPreferredSize(new java.awt.Dimension(30, 30));
        colorBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBlueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBlueLayout = new javax.swing.GroupLayout(colorBlue);
        colorBlue.setLayout(colorBlueLayout);
        colorBlueLayout.setHorizontalGroup(
            colorBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorBlueLayout.setVerticalGroup(
            colorBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorLightPink.setBackground(new java.awt.Color(255, 102, 204));
        colorLightPink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorLightPink.setPreferredSize(new java.awt.Dimension(30, 30));
        colorLightPink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLightPinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorLightPinkLayout = new javax.swing.GroupLayout(colorLightPink);
        colorLightPink.setLayout(colorLightPinkLayout);
        colorLightPinkLayout.setHorizontalGroup(
            colorLightPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorLightPinkLayout.setVerticalGroup(
            colorLightPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorBrown.setBackground(new java.awt.Color(51, 0, 0));
        colorBrown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorBrown.setPreferredSize(new java.awt.Dimension(30, 30));
        colorBrown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBrownMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorBrownLayout = new javax.swing.GroupLayout(colorBrown);
        colorBrown.setLayout(colorBrownLayout);
        colorBrownLayout.setHorizontalGroup(
            colorBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorBrownLayout.setVerticalGroup(
            colorBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorDarkBlue.setBackground(new java.awt.Color(0, 0, 102));
        colorDarkBlue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorDarkBlue.setPreferredSize(new java.awt.Dimension(30, 30));
        colorDarkBlue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorDarkBlueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorDarkBlueLayout = new javax.swing.GroupLayout(colorDarkBlue);
        colorDarkBlue.setLayout(colorDarkBlueLayout);
        colorDarkBlueLayout.setHorizontalGroup(
            colorDarkBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorDarkBlueLayout.setVerticalGroup(
            colorDarkBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorLightBrown.setBackground(new java.awt.Color(102, 51, 0));
        colorLightBrown.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorLightBrown.setPreferredSize(new java.awt.Dimension(30, 30));
        colorLightBrown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLightBrownMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorLightBrownLayout = new javax.swing.GroupLayout(colorLightBrown);
        colorLightBrown.setLayout(colorLightBrownLayout);
        colorLightBrownLayout.setHorizontalGroup(
            colorLightBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorLightBrownLayout.setVerticalGroup(
            colorLightBrownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorNavy.setBackground(new java.awt.Color(0, 0, 51));
        colorNavy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorNavy.setPreferredSize(new java.awt.Dimension(30, 30));
        colorNavy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorNavyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorNavyLayout = new javax.swing.GroupLayout(colorNavy);
        colorNavy.setLayout(colorNavyLayout);
        colorNavyLayout.setHorizontalGroup(
            colorNavyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorNavyLayout.setVerticalGroup(
            colorNavyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorPurple.setBackground(new java.awt.Color(51, 0, 102));
        colorPurple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorPurple.setPreferredSize(new java.awt.Dimension(30, 30));
        colorPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorPurpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorPurpleLayout = new javax.swing.GroupLayout(colorPurple);
        colorPurple.setLayout(colorPurpleLayout);
        colorPurpleLayout.setHorizontalGroup(
            colorPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorPurpleLayout.setVerticalGroup(
            colorPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorLightPurple.setBackground(new java.awt.Color(204, 0, 204));
        colorLightPurple.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorLightPurple.setPreferredSize(new java.awt.Dimension(30, 30));
        colorLightPurple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorLightPurpleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorLightPurpleLayout = new javax.swing.GroupLayout(colorLightPurple);
        colorLightPurple.setLayout(colorLightPurpleLayout);
        colorLightPurpleLayout.setHorizontalGroup(
            colorLightPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorLightPurpleLayout.setVerticalGroup(
            colorLightPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorPink.setBackground(new java.awt.Color(255, 0, 153));
        colorPink.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorPink.setPreferredSize(new java.awt.Dimension(30, 30));
        colorPink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorPinkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorPinkLayout = new javax.swing.GroupLayout(colorPink);
        colorPink.setLayout(colorPinkLayout);
        colorPinkLayout.setHorizontalGroup(
            colorPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorPinkLayout.setVerticalGroup(
            colorPinkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorDarkGreen.setBackground(new java.awt.Color(0, 102, 0));
        colorDarkGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorDarkGreen.setPreferredSize(new java.awt.Dimension(30, 30));
        colorDarkGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorDarkGreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorDarkGreenLayout = new javax.swing.GroupLayout(colorDarkGreen);
        colorDarkGreen.setLayout(colorDarkGreenLayout);
        colorDarkGreenLayout.setHorizontalGroup(
            colorDarkGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorDarkGreenLayout.setVerticalGroup(
            colorDarkGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorRed.setBackground(new java.awt.Color(255, 0, 0));
        colorRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorRed.setPreferredSize(new java.awt.Dimension(30, 30));
        colorRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorRedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorRedLayout = new javax.swing.GroupLayout(colorRed);
        colorRed.setLayout(colorRedLayout);
        colorRedLayout.setHorizontalGroup(
            colorRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorRedLayout.setVerticalGroup(
            colorRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorOrange.setBackground(new java.awt.Color(255, 51, 0));
        colorOrange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorOrange.setPreferredSize(new java.awt.Dimension(30, 30));
        colorOrange.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorOrangeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorOrangeLayout = new javax.swing.GroupLayout(colorOrange);
        colorOrange.setLayout(colorOrangeLayout);
        colorOrangeLayout.setHorizontalGroup(
            colorOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorOrangeLayout.setVerticalGroup(
            colorOrangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorDarkYellow.setBackground(new java.awt.Color(153, 153, 0));
        colorDarkYellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorDarkYellow.setPreferredSize(new java.awt.Dimension(30, 30));
        colorDarkYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorDarkYellowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorDarkYellowLayout = new javax.swing.GroupLayout(colorDarkYellow);
        colorDarkYellow.setLayout(colorDarkYellowLayout);
        colorDarkYellowLayout.setHorizontalGroup(
            colorDarkYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorDarkYellowLayout.setVerticalGroup(
            colorDarkYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorYellow.setBackground(new java.awt.Color(255, 255, 0));
        colorYellow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorYellow.setPreferredSize(new java.awt.Dimension(30, 30));
        colorYellow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorYellowMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorYellowLayout = new javax.swing.GroupLayout(colorYellow);
        colorYellow.setLayout(colorYellowLayout);
        colorYellowLayout.setHorizontalGroup(
            colorYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorYellowLayout.setVerticalGroup(
            colorYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        colorGreen.setBackground(new java.awt.Color(0, 255, 0));
        colorGreen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        colorGreen.setPreferredSize(new java.awt.Dimension(30, 30));
        colorGreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorGreenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout colorGreenLayout = new javax.swing.GroupLayout(colorGreen);
        colorGreen.setLayout(colorGreenLayout);
        colorGreenLayout.setHorizontalGroup(
            colorGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        colorGreenLayout.setVerticalGroup(
            colorGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushTypeRound = new BrushTypeRound();
        brushTypeRound.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushTypeRound.setAlignmentX(0.0F);
        brushTypeRound.setAlignmentY(0.0F);
        brushTypeRound.setPreferredSize(new java.awt.Dimension(30, 30));
        brushTypeRound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushTypeRoundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushTypeRoundLayout = new javax.swing.GroupLayout(brushTypeRound);
        brushTypeRound.setLayout(brushTypeRoundLayout);
        brushTypeRoundLayout.setHorizontalGroup(
            brushTypeRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushTypeRoundLayout.setVerticalGroup(
            brushTypeRoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushTypeSquare = new BrushTypeSquare();
        brushTypeSquare.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushTypeSquare.setAlignmentX(0.0F);
        brushTypeSquare.setAlignmentY(0.0F);
        brushTypeSquare.setPreferredSize(new java.awt.Dimension(30, 30));
        brushTypeSquare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushTypeSquareMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushTypeSquareLayout = new javax.swing.GroupLayout(brushTypeSquare);
        brushTypeSquare.setLayout(brushTypeSquareLayout);
        brushTypeSquareLayout.setHorizontalGroup(
            brushTypeSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushTypeSquareLayout.setVerticalGroup(
            brushTypeSquareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushSize1 = new BrushSize(1);
        brushSize1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushSize1.setAlignmentX(0.0F);
        brushSize1.setAlignmentY(0.0F);
        brushSize1.setPreferredSize(new java.awt.Dimension(30, 30));
        brushSize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushSize1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushSize1Layout = new javax.swing.GroupLayout(brushSize1);
        brushSize1.setLayout(brushSize1Layout);
        brushSize1Layout.setHorizontalGroup(
            brushSize1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushSize1Layout.setVerticalGroup(
            brushSize1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushSize5 = new BrushSize(5);
        brushSize5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushSize5.setAlignmentX(0.0F);
        brushSize5.setAlignmentY(0.0F);
        brushSize5.setPreferredSize(new java.awt.Dimension(30, 30));
        brushSize5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushSize5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushSize5Layout = new javax.swing.GroupLayout(brushSize5);
        brushSize5.setLayout(brushSize5Layout);
        brushSize5Layout.setHorizontalGroup(
            brushSize5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushSize5Layout.setVerticalGroup(
            brushSize5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushSize10 = new BrushSize(10);
        brushSize10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushSize10.setAlignmentX(0.0F);
        brushSize10.setAlignmentY(0.0F);
        brushSize10.setPreferredSize(new java.awt.Dimension(30, 30));
        brushSize10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushSize10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushSize10Layout = new javax.swing.GroupLayout(brushSize10);
        brushSize10.setLayout(brushSize10Layout);
        brushSize10Layout.setHorizontalGroup(
            brushSize10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushSize10Layout.setVerticalGroup(
            brushSize10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        brushSize15 = new BrushSize(15);
        brushSize15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        brushSize15.setAlignmentX(0.0F);
        brushSize15.setAlignmentY(0.0F);
        brushSize15.setPreferredSize(new java.awt.Dimension(30, 30));
        brushSize15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brushSize15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout brushSize15Layout = new javax.swing.GroupLayout(brushSize15);
        brushSize15.setLayout(brushSize15Layout);
        brushSize15Layout.setHorizontalGroup(
            brushSize15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        brushSize15Layout.setVerticalGroup(
            brushSize15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorLightGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorDarkCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorLightBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorDarkBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorNavy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorLightPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorLightPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorLightBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorDarkYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(colorGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(colorDarkGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(brushTypeRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brushTypeSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(brushSize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brushSize5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(brushSize10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brushSize15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorBlack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorWhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLightGray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorDarkCyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorLightBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorDarkBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorNavy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLightPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLightPink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorLightBrown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorOrange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorDarkYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorYellow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(colorGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorDarkGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brushTypeRound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brushTypeSquare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brushSize1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brushSize5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(brushSize10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brushSize15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItem1.setText("New");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Save");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Save as");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Exit");
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem6.setText("Clear");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Add Image");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Copy to Clipboard");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorBlackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBlackMouseClicked
        // TODO add your handling code here:
        brushColor = Color.BLACK;
        clearColorBorders();
        colorBlack.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorBlackMouseClicked

    private void colorWhiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorWhiteMouseClicked
        // TODO add your handling code here:
        brushColor = Color.WHITE;
        clearColorBorders();
        colorWhite.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorWhiteMouseClicked

    private void colorGrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorGrayMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(102,102,102);
        clearColorBorders();
        colorGray.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorGrayMouseClicked

    private void colorLightGrayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLightGrayMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(204,204,204);
        clearColorBorders();
        colorLightGray.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorLightGrayMouseClicked

    private void colorCyanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorCyanMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,255,255);
        clearColorBorders();
        colorCyan.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorCyanMouseClicked

    private void colorDarkCyanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorDarkCyanMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,51,51);
        clearColorBorders();
        colorDarkCyan.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorDarkCyanMouseClicked

    private void colorLightBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLightBlueMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,153,255);
        clearColorBorders();
        colorLightBlue.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorLightBlueMouseClicked

    private void colorBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBlueMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,0,255);
        clearColorBorders();
        colorBlue.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorBlueMouseClicked

    private void colorDarkBlueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorDarkBlueMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,0,102);
        clearColorBorders();
        colorDarkBlue.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorDarkBlueMouseClicked

    private void colorNavyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorNavyMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,0,51);
        clearColorBorders();
        colorNavy.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorNavyMouseClicked

    private void colorPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorPurpleMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(51,0,102);
        clearColorBorders();
        colorPurple.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorPurpleMouseClicked

    private void colorLightPurpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLightPurpleMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(204,0,204);
        clearColorBorders();
        colorLightPurple.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorLightPurpleMouseClicked

    private void colorPinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorPinkMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(255,0,153);
        clearColorBorders();
        colorPink.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorPinkMouseClicked

    private void colorLightPinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLightPinkMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(255,102,204);
        clearColorBorders();
        colorLightPink.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorLightPinkMouseClicked

    private void colorBrownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorBrownMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(51,0,0);
        clearColorBorders();
        colorBrown.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorBrownMouseClicked

    private void colorLightBrownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorLightBrownMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(102,51,0);
        clearColorBorders();
        colorLightBrown.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorLightBrownMouseClicked

    private void colorRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorRedMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(255,0,0);
        clearColorBorders();
        colorRed.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorRedMouseClicked

    private void colorOrangeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorOrangeMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(255,51,0);
        clearColorBorders();
        colorOrange.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorOrangeMouseClicked

    private void colorDarkYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorDarkYellowMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(153,153,0);
        clearColorBorders();
        colorDarkYellow.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorDarkYellowMouseClicked

    private void colorYellowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorYellowMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(255,255,0);
        clearColorBorders();
        colorYellow.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorYellowMouseClicked

    private void colorGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorGreenMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,255,0);
        clearColorBorders();
        colorGreen.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorGreenMouseClicked

    private void colorDarkGreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorDarkGreenMouseClicked
        // TODO add your handling code here:
        brushColor = new Color(0,102,0);
        clearColorBorders();
        colorDarkGreen.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_colorDarkGreenMouseClicked

    private void brushTypeRoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushTypeRoundMouseClicked
        // TODO add your handling code here:
        brushType = 1;
        clearTypeBorders();
        brushTypeRound.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushTypeRoundMouseClicked

    private void brushTypeSquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushTypeSquareMouseClicked
        // TODO add your handling code here:
        brushType = 2;
        clearTypeBorders();
        brushTypeSquare.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushTypeSquareMouseClicked

    private void brushSize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushSize1MouseClicked
        // TODO add your handling code here:
        brushSize = 2;
        clearSizeBorders();
        brushSize1.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushSize1MouseClicked

    private void brushSize5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushSize5MouseClicked
        // TODO add your handling code here:
        brushSize = 6;
        clearSizeBorders();
        brushSize5.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushSize5MouseClicked

    private void brushSize10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushSize10MouseClicked
        // TODO add your handling code here:
        brushSize = 10;
        clearSizeBorders();
        brushSize10.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushSize10MouseClicked

    private void brushSize15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brushSize15MouseClicked
        // TODO add your handling code here:
        brushSize = 16;
        clearSizeBorders();
        brushSize15.setBorder(new LineBorder(Color.BLUE));
    }//GEN-LAST:event_brushSize15MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        Graphics2D g2d = (Graphics2D) jPanel2.getGraphics();
        g2d.setColor(brushColor);
        if(brushType==1){
            g2d.fillOval(evt.getX(), evt.getY(), brushSize, brushSize);
        }else{
            g2d.fillRect(evt.getX(), evt.getY(), brushSize, brushSize);
        }
        String action = (brushColor.getRed()+","+brushColor.getGreen()+","+brushColor.getBlue());
        action += ";"+brushType+";"+brushSize+";"+evt.getX()+","+evt.getY();
        conexao.atualizar(action);
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        Graphics2D g2d = (Graphics2D) jPanel2.getGraphics();
        g2d.setColor(brushColor);
        if(brushType==1){
            g2d.fillOval(evt.getX(), evt.getY(), brushSize, brushSize);
        }else{
            g2d.fillRect(evt.getX(), evt.getY(), brushSize, brushSize);
        }
        String action = (brushColor.getRed()+","+brushColor.getGreen()+","+brushColor.getBlue());
        action += ";"+brushType+";"+brushSize+";"+evt.getX()+","+evt.getY();
        conexao.atualizar(action);
    }//GEN-LAST:event_jPanel2MouseDragged


    private void clearColorBorders(){
        colorBlack.setBorder(new LineBorder(Color.BLACK));
        colorBlue.setBorder(new LineBorder(Color.BLACK));
        colorBrown.setBorder(new LineBorder(Color.BLACK));
        colorCyan.setBorder(new LineBorder(Color.BLACK));
        colorDarkBlue.setBorder(new LineBorder(Color.BLACK));
        colorDarkCyan.setBorder(new LineBorder(Color.BLACK));
        colorDarkGreen.setBorder(new LineBorder(Color.BLACK));
        colorDarkYellow.setBorder(new LineBorder(Color.BLACK));
        colorGray.setBorder(new LineBorder(Color.BLACK));
        colorGreen.setBorder(new LineBorder(Color.BLACK));
        colorLightBlue.setBorder(new LineBorder(Color.BLACK));
        colorLightBrown.setBorder(new LineBorder(Color.BLACK));
        colorLightGray.setBorder(new LineBorder(Color.BLACK));
        colorLightPink.setBorder(new LineBorder(Color.BLACK));
        colorLightPurple.setBorder(new LineBorder(Color.BLACK));
        colorNavy.setBorder(new LineBorder(Color.BLACK));
        colorOrange.setBorder(new LineBorder(Color.BLACK));
        colorPink.setBorder(new LineBorder(Color.BLACK));
        colorPurple.setBorder(new LineBorder(Color.BLACK));
        colorRed.setBorder(new LineBorder(Color.BLACK));
        colorWhite.setBorder(new LineBorder(Color.BLACK));
        colorYellow.setBorder(new LineBorder(Color.BLACK));
    }

    private void clearTypeBorders(){
        brushTypeRound.setBorder(new LineBorder(Color.BLACK));
        brushTypeSquare.setBorder(new LineBorder(Color.BLACK));
    }

    private void clearSizeBorders(){
        brushSize1.setBorder(new LineBorder(Color.BLACK));
        brushSize5.setBorder(new LineBorder(Color.BLACK));
        brushSize10.setBorder(new LineBorder(Color.BLACK));
        brushSize15.setBorder(new LineBorder(Color.BLACK));
    }


    public void enviar(){
        try {
            output.writeObject(p);
        } catch (IOException ex) {
            Logger.getLogger(Conexao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    protected void processWindowEvent(WindowEvent e){
        if(e.getID() == WindowEvent.WINDOW_CLOSING){
            try {
                conexao.atualizar("quit");
                if(socket!=null)
                    socket.close();
                conexao.close();
            } catch (IOException ex) {
                Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        super.processWindowEvent(e);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
                Cliente c = new Cliente();
                c.setVisible(true);
                c.conexao.start();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brushSize1;
    private javax.swing.JPanel brushSize10;
    private javax.swing.JPanel brushSize15;
    private javax.swing.JPanel brushSize5;
    private javax.swing.JPanel brushTypeRound;
    private javax.swing.JPanel brushTypeSquare;
    private javax.swing.JPanel colorBlack;
    private javax.swing.JPanel colorBlue;
    private javax.swing.JPanel colorBrown;
    private javax.swing.JPanel colorCyan;
    private javax.swing.JPanel colorDarkBlue;
    private javax.swing.JPanel colorDarkCyan;
    private javax.swing.JPanel colorDarkGreen;
    private javax.swing.JPanel colorDarkYellow;
    private javax.swing.JPanel colorGray;
    private javax.swing.JPanel colorGreen;
    private javax.swing.JPanel colorLightBlue;
    private javax.swing.JPanel colorLightBrown;
    private javax.swing.JPanel colorLightGray;
    private javax.swing.JPanel colorLightPink;
    private javax.swing.JPanel colorLightPurple;
    private javax.swing.JPanel colorNavy;
    private javax.swing.JPanel colorOrange;
    private javax.swing.JPanel colorPink;
    private javax.swing.JPanel colorPurple;
    private javax.swing.JPanel colorRed;
    private javax.swing.JPanel colorWhite;
    private javax.swing.JPanel colorYellow;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
    private int brushType;
    private int brushSize;
    private Color brushColor;
    private Conexao conexao;
}
